import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Editor, { DiffEditor, useMonaco, loader } from "@monaco-editor/react";
import axios from 'axios';
import { useUserContext } from '../../utils/context';
import verifyHolder from '../../utils/verifyHolder';
import { inspect } from 'util';
import connectionManager from '../../utils/connection';

const ResponsiveImage = (props) => (
  <Image alt={props.alt} layout="responsive" {...props} />
)


export default function TestEditor(props) {

  const [editorContent, setEditorContent] = useState('// ayoooo')
  const {ctx, setCtx} = useUserContext()
  const { connect, reset } = connectionManager(ctx, setCtx)

  // const validateToken = async () => {
    
  // }
  
  // useEffect(()=>{

  //   ;(async ()=>{
  //     console.log('editor | validating token...')
  //     await axios.post('/api/verify-jwt', {address: ctx.w3m.provider.selectedAddress ? ctx.w3m.provider.selectedAddress : ctx.w3m.provider.accounts[0]})
  //   })();

  // }, [ctx])

    useEffect(()=>{

    ;(async ()=>{
      if(!ctx.connected){
        connect()
      }
      verifyHolder(ctx.address)
    })();

  }, [ctx])




  const components = {
    img: ResponsiveImage,
    // h1: Heading.H1,
    // h2: Heading.H2,
    // p: Text,
    // pre: Pre,
    // code: InlineCode,
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


       <main className={styles.main}>
      <p>Monaco - Next.js</p>

      <Editor
        height="60vh"
        defaultLanguage="sol"
        value={editorContent}
        onChange={setEditorContent}
        theme={'vs-dark'}
      /> 


      <pre>{inspect(ctx)}</pre>



      </main> 
   
    </div>
  )
}
