
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useUserContext } from '../utils/context'

export default function Home(props) {
  const {ctx, setCtx} = useUserContext()



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>index.js - Home</p>

      <pre>{JSON.stringify(ctx)}</pre>

      <button onClick={() => setCtx({...ctx, newData: 'New Context!'})}>Set CTX</button>


   
    </div>
  )
}