import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Editor, { DiffEditor, useMonaco, loader } from "@monaco-editor/react";

export default function Home() {

  const [editorContent, setEditorContent] = useState<any>('// ayoooo')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <p>Monaco - Next.js</p>

      <Editor
        height="60vh"
        defaultLanguage="sol"
        value={editorContent}
        onChange={setEditorContent}
        theme={'vs-dark'}
      />



      </main>
   
    </div>
  )
}
